// Mirror of server/columns.ts kept identical so the live table matches the downloaded CSV.
// When changing column order, update both files in lockstep.

export const CSV_COLUMN_ORDER: readonly string[] = [
  'Company Name',
  'Reason for Rejection',
  'Final Score',
  'Company Context Score',
  'Tooling Match Score',
  'Intent Signal Score',
  'Digital Native',
  'Website',
  'Industry',
  'Number of Users',
  'Observability Tool',
  'Communication Tool',
  'Cloud Tool',
  'Funding Growth',
  'Revenue Growth',
  'Number of Engineers',
  'Number of SREs',
  'Engineer Hiring',
  'SRE Hiring',
  'Customer complains on X',
  'Recent incidents ( Official )',
  'AI adoption mindset',
  'AI SRE maturity',
  'Competitor Tooling',
  'Domain',
  'Description',
  'LinkedIn Page',
  'Apollo ID',
  'Account Purpose',
  'Company Context Score Change Detection for Developer',
  'Tooling Match Change Detection for Developer',
  'Intent Signal Change Detection for Developer',
  'Final Score Change Detection for Developer',
];

export const STAGE_COLUMNS = new Set<string>([
  'Final Score',
  'Company Context Score',
  'Tooling Match Score',
  'Intent Signal Score',
  'Digital Native',
  'Industry',
  'Number of Users',
  'Observability Tool',
  'Communication Tool',
  'Cloud Tool',
  'Funding Growth',
  'Revenue Growth',
  'Number of Engineers',
  'Number of SREs',
  'Engineer Hiring',
  'SRE Hiring',
  'Customer complains on X',
  'Recent incidents ( Official )',
  'AI adoption mindset',
  'AI SRE maturity',
  'Competitor Tooling',
]);

export const DEVELOPER_COLUMNS = new Set<string>([
  'Company Context Score Change Detection for Developer',
  'Tooling Match Change Detection for Developer',
  'Intent Signal Change Detection for Developer',
  'Final Score Change Detection for Developer',
]);

// Score columns get tabular-nums + the mono font and a slightly different visual weight
export const SCORE_COLUMNS = new Set<string>([
  'Final Score',
  'Company Context Score',
  'Tooling Match Score',
  'Intent Signal Score',
]);

// Compact column-display widths for the live table (in px). Numbers favor scanning the score
// columns at a glance; long-text columns get a clip-with-tooltip treatment below.
export const COLUMN_WIDTHS: Record<string, number> = {
  'Company Name': 200,
  'Reason for Rejection': 220,
  'Final Score': 150,
  'Company Context Score': 130,
  'Tooling Match Score': 130,
  'Intent Signal Score': 130,
  'Digital Native': 220,
  'Website': 180,
  'Industry': 160,
  'Number of Users': 150,
  'Observability Tool': 200,
  'Communication Tool': 180,
  'Cloud Tool': 160,
  'Funding Growth': 220,
  'Revenue Growth': 220,
  'Number of Engineers': 130,
  'Number of SREs': 130,
  'Engineer Hiring': 200,
  'SRE Hiring': 200,
  'Customer complains on X': 220,
  'Recent incidents ( Official )': 220,
  'AI adoption mindset': 240,
  'AI SRE maturity': 240,
  'Competitor Tooling': 220,
  'Domain': 180,
  'Description': 260,
  'LinkedIn Page': 220,
  'Apollo ID': 160,
  'Account Purpose': 180,
  'Company Context Score Change Detection for Developer': 200,
  'Tooling Match Change Detection for Developer': 200,
  'Intent Signal Change Detection for Developer': 200,
  'Final Score Change Detection for Developer': 200,
};
