import type { StageCompany, StageResult } from './types.js';
import type { ApolloApiSearchResponse } from '../apis/apollo.js';

export const ENGINEER_TITLES = [
  'engineer',
  'developer',
  'IOS',
  'mobile',
  'android',
  'platform',
  'infrastructure',
  'devops',
  'SRE',
  'Site Reliability',
  'ML',
  'AI',
  'machine learning',
  'database',
  'builder',
  'backend',
  'frontend',
  'back-end',
  'back end',
  'front-end',
  'front end',
  'cloud',
  'data',
  'deep learning',
  'programmer',
  'architect',
  'technician',
  'coder',
  'engineering manager',
  'chief technology officer',
  'cto',
  'engineering',
  'tech lead',
  'technical lead',
  'principal',
  'staff',
  'engineering intern',
  'technical intern',
  'QA',
  'quality assurance',
  'tester',
  'SDET',
  'test automation',
  'quality engineer',
  'technical program manager',
  'TPM',
  'engineering program manager',
  'release manager',
  'release engineer',
  'build engineer',
  'scrum master',
  'agile coach',
  'security analyst',
  'penetration tester',
  'pen tester',
  'vulnerability',
  'cryptographer',
  'cybersecurity',
  'applied scientist',
  'research scientist',
  'computational',
  'simulation',
  'algorithm',
  'computer scientist',
  'technologist',
  'FPGA',
  'VLSI',
  'CAD',
  'PCB',
  'circuit design',
  'chip design',
  'semiconductor',
  'robotics',
  'mechatronics',
  'mechanical design',
  'systems integration',
  'network administrator',
  'network operations',
  'network analyst',
  'NOC',
  'systems administrator',
  'sysadmin',
  'IT operations',
  'helpdesk engineer',
  'support engineer',
  'technical support',
  'data scientist',
  'data analyst',
  'DBA',
  'ETL',
  'data modeler',
  'solutions consultant',
  'implementation consultant',
  'integration consultant',
  'technical',
  'TAM',
  'webmaster',
  'fullstack',
  'full stack',
] as const;

export type NumberOfEngineersData = {
  count: number;
};

export function parseNumberOfEngineersResponse(
  raw: ApolloApiSearchResponse,
  companies: StageCompany[]
): StageResult<NumberOfEngineersData>[] {
  const company = companies[0];
  if (!company) return [];
  return [{ company, data: { count: raw.total_entries ?? 0 } }];
}

export function formatNumberOfEngineersForAttio(d: NumberOfEngineersData): string {
  return String(d.count);
}
